Repository DarrenVs/Cuboid, pull requests merged in 2018-06, with the labels that each got.

#57 Fixed Warp Particles (V3.1.1)
  Content/Effects/ParticleSystems/PS_Warp.uasset
Labels: progress

#62 Added Particles for Hexcoin Pickup (V3.4.1)
  Content/Effects/Materials/M_Beam.uasset
  Content/Effects/ParticleSystems/PS_HexcoinPickup.uasset
Labels: enhancement

#64 Fixed Tube Material (V3.6.1)
  Content/Materials/M_PositionTest_2.uasset
Labels: progress

#58 Fixed Player Collision Particles (V3.1.2)
  Content/Effects/Materials/M_Smoke.uasset
  Content/Effects/ParticleSystems/PS_PlayerCollision.uasset
  Content/Effects/ParticleSystems/PS_Warp.uasset
Labels: progress

#61 lighting test1
  Content/Blueprints/BP_Chunk.uasset
  Content/Blueprints/ChunkGen/BP_ChunkGenerator_Tube_Chunk.uasset
  Content/Effects/Materials/CutOff/CutoffDissolve/MF_CutOff.uasset
  Content/Effects/Materials/CutOff/CutoffDissolve/MI_CutOff.uasset
  Content/Effects/Materials/CutOff/CutoffDissolve/M_CutOff.uasset
  Content/Effects/Materials/CutOff/MF_CutOff.uasset
  Content/Effects/Materials/CutOff/MI_CutOff.uasset
  Content/Effects/Materials/CutOff/M_CutOff.uasset
  Content/Effects/Materials/CutOff/Position.uasset
  Content/Effects/Materials/Dissolve/MF_Dissolve.uasset
  Content/Effects/Materials/Dissolve/M_Dissolve.uasset
  Content/Effects/Materials/Dissolve/M_Dissolve_Inst.uasset
  Content/Geometry/Meshes/Environment/Materials/M_Master.uasset
  Content/Maps/PlayableScene/PLAYABLE.umap
  Content/Maps/TestMaps/ChunkGeneration.umap
  Content/Maps/TestMaps/lighting/lightingtest1.umap
  Content/Meshes/ChunkBase/M_UE4Man_Body1.uasset
  Content/Meshes/ChunkBase/M_UE4Man_ChestLogo1.uasset
  Content/Meshes/ChunkBase/Tube001.uasset
  Content/Meshes/ChunkBase/Tube002.uasset
  Content/Meshes/ChunkBase/chunk_template.uasset
  Content/VirtualRealityBP/Maps/StartupMap.umap
Labels: progress

#66 Lighting changes2
  Content/Maps/TestMaps/ChunkGeneration.umap
  Content/Materials/M_PositionTest_2.uasset
Labels: enhancement

#67 Added code conventions (v3.6.1)
  Content/Blueprints/feature_player_movement/BP_CameraBehaviour.uasset
  Content/Blueprints/feature_player_movement/BP_PlayerBehaviour.uasset
  Content/Blueprints/feature_player_movement/BP_PlayerMovement.uasset
  Content/Blueprints/feature_player_movement/BP_Player_Movement.uasset
  Content/Blueprints/feature_playermovement_refactor/BP_Default_Fly_Camera.uasset
  Content/Blueprints/feature_playermovement_refactor/BP_Flying_Character.uasset
  Content/Blueprints/feature_playermovement_refactor/Flying_Input_Default.uasset
Labels: progress

#68 Lighting
  Content/Maps/TestMaps/ChunkGeneration.umap
  Content/Materials/M_PositionTest_2.uasset
  Content/Materials/material_tube/lines_alpha.uasset
  Content/Materials/material_tube/scan_line_3.uasset
  Content/Meshes/Characters/Player/Materials/M_DonDiablo_Body.uasset
Labels: progress

#71 Menu items
  Content/Geometry/Meshes/Menu/Materials/MI_UI_Exit.uasset
  Content/Geometry/Meshes/Menu/Materials/MI_UI_Leaderboard.uasset
  Content/Geometry/Meshes/Menu/Materials/MI_UI_Start.uasset
  Content/Geometry/Meshes/Menu/Materials/M_UI.uasset
  Content/Geometry/Meshes/Menu/Meshes/UI_Exit.uasset
  Content/Geometry/Meshes/Menu/Meshes/UI_Leaderboard.uasset
  Content/Geometry/Meshes/Menu/Meshes/UI_Start.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Exitgame_AORMT.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Exitgame_BC.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Exitgame_EM.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Exitgame_N.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Leaderboard_AORMT.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Leaderboard_BC.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Leaderboard_EM.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Leaderboard_N.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Startgame_AORMT.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Startgame_BC.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Startgame_EM.uasset
  Content/Geometry/Meshes/Menu/Textures/T_UI_Startgame_N.uasset
Labels: enhancement

#69 Character blueprint prepared for character customization
  Content/Blueprints/feature_playermovement_refactor/BP_Flying_Character.uasset
  Content/Effects/Materials/M_Sparks.uasset
  Content/Effects/Materials/RibbonTrail.uasset
  Content/Effects/ParticleSystems/PS_RibbonTrailer.uasset
  Content/Effects/RibbonPhysics/Ribbon.uasset
  Content/Effects/RibbonPhysics/Ribbon_PhysicsAsset.uasset
  Content/Effects/RibbonPhysics/Ribbon_Skeleton.uasset
  Content/Meshes/Characters/Player/Materials/M_DonDiablo_JetPackv5.uasset
  Content/Meshes/Characters/Player/Meshes/DonDiablo_Skeleton.uasset
  Content/Meshes/Characters/Player/Meshes/Jetpackv4/SM_Jetpack_v4.uasset
  Content/Meshes/Characters/Player/Meshes/Jetpackv5/SM_jetpack_V5.uasset
  Content/Meshes/Characters/Player/Meshes/SK_DonDiablo.uasset
  Content/Meshes/Characters/Player/Textures/Jetpack_v5/T_jetpackv5_AORMT.uasset
  Content/Meshes/Characters/Player/Textures/Jetpack_v5/T_jetpackv5_BC.uasset
  Content/Meshes/Characters/Player/Textures/Jetpack_v5/T_jetpackv5_N.uasset
  Content/SK_DonDiablo_Blueprint.uasset
Labels: enhancement

#70 updated lighting and a lot of other small tweaks and fixes
  Content/AdvancedFresnelSegment/matFresnelSegment_Inst.uasset
  Content/Blueprints/feature_character_behaviour/Fly_Blendspace.uasset
  Content/Blueprints/feature_character_behaviour/Flying_Behaviour.uasset
  Content/Blueprints/feature_playermovement_refactor/Flying_Input_Default.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Building_Class_B_02.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Building_Class_C_02.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Building_Class_C_05.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Building_Class_D_03.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Building_Class_D_05.uasset
  Content/Geometry/Meshes/Environment/Materials/M_Master.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_Class_B_01.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_Class_B_02.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_Class_B_03.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_Class_B_04.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_Class_C_02.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_Class_D_01.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_class_C_05.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Bulding_Class_D_03.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_building_class_C_01.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_building_class_D_05.uasset
  Content/Maps/TestMaps/ChunkGeneration.umap
  Content/Materials/M_PositionTest_2.uasset
  Content/Meshes/Characters/Player/Meshes/Animations/DonDiablo_BottomLeft.uasset
  Content/Meshes/Characters/Player/Meshes/Animations/DonDiablo_BottomRight.uasset
  Content/Meshes/Characters/Player/Meshes/Animations/DonDiablo_Fly.uasset
  Content/Meshes/Characters/Player/Meshes/Animations/DonDiablo_Hurt.uasset
  Content/Meshes/Characters/Player/Meshes/Animations/DonDiablo_LeftTumble.uasset
  Content/Meshes/Characters/Player/Meshes/Animations/DonDiablo_RightTumble.uasset
  Content/Meshes/Characters/Player/Meshes/Animations/DonDiablo_TopLeft.uasset
  Content/Meshes/Characters/Player/Meshes/Animations/DonDiablo_TopRight.uasset
Labels: progress

#72 Added Static Mesh of Highway (V3.7.1)
  Content/Geometry/Meshes/Environment/Meshes/MiscObjects/SM_Highway_Highway.uasset
Labels: enhancement

#77 Feature tube material
  Content/Geometry/Meshes/Environment/Materials/MI_building_class_B_06.uasset
  Content/Geometry/Meshes/Environment/Meshes/MiscObjects/tram/SM_Tram_Tunnel.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_class_B_06.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_B_06/T_SM_Building_class_B_06_AORMT.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_B_06/T_SM_Building_class_B_06_BC.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_B_06/T_SM_Building_class_B_06_EM.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_B_06/T_SM_Building_class_B_06_N.uasset
Labels: enhancement

#74 Added Materials to Billboards and changed PS_Thruster (V3.7.2)
  Content/Effects/Materials/MI_HologramStatic_DonLogo.uasset
  Content/Effects/Materials/MI_HologramStatic_DonNews.uasset
  Content/Effects/Materials/MI_HologramStatic_Skull.uasset
  Content/Effects/Materials/M_Hologram_Static.uasset
  Content/Effects/Materials/M_Thruster.uasset
  Content/Effects/ParticleSystems/PS_Thruster.uasset
  Content/Effects/Textures/DonDiabloSkullHologram.uasset
  Content/Effects/Textures/don_met_logo_2.uasset
  Content/Geometry/Meshes/Environment/Meshes/Billboards/SM_Billboard_1.uasset
  Content/Geometry/Meshes/Environment/Meshes/Billboards/SM_Billboard_2.uasset
  Content/Geometry/Meshes/Environment/Meshes/Billboards/SM_Billboard_3.uasset
  Content/Geometry/Meshes/Environment/Meshes/Billboards/SM_Billboard_4.uasset
  Content/Geometry/Meshes/Environment/Meshes/Billboards/SM_Billboard_5.uasset
Labels: enhancement

#76 Menu implementation into the main feature.
  Content/Blueprints/Menu/BP_MainMenu.uasset
  Content/Effects/Materials/CutOff/MF_CutOff.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Billboard_02.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Building_Class_C_05.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Hijskraan01.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_level_door.uasset
  Content/Geometry/Meshes/Environment/Materials/M_Master.uasset
  Content/Geometry/Meshes/Menu/Materials/MI_UI_Start.uasset
  Content/Maps/Menu/MainMenu.umap
  Content/Maps/Menu/WBP_MainMenu.uasset
Labels: enhancement

#78 building manager changes and new buildings import
  Content/Blueprints/BuildingClass/BP_BuildingManager.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Building_Class_C_06.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Highway.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_building_class_B_06.uasset
  Content/Geometry/Meshes/Environment/Meshes/MiscObjects/tram/SM_Tram_Tunnel.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_class_B_06.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_buildings_class_C_06.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_c_06/T_building_class_C_06_AORMT.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_c_06/T_building_class_C_06_BC.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_c_06/T_building_class_C_06_EM.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_c_06/T_building_class_C_06_N.uasset
  Content/Maps/TestMaps/ChunkGeneration.umap
Labels: enhancement, progress

#80 V3.8.2 Instancing buildings
  Content/Blueprints/BP_AudioManager.uasset
  Content/Blueprints/BP_ChunkManager.uasset
  Content/Blueprints/BuildingClass/BP_BuildingClass.uasset
  Content/Blueprints/BuildingClass/BP_BuildingManager.uasset
  Content/Blueprints/ChunkGen/BP_ChunkGenerator_Tube.uasset
  Content/Blueprints/ChunkGen/BP_ChunkGenerator_Tube_Chunk.uasset
  Content/Blueprints/ChunkGen/BP_ChunkGenerator_Tube_InstanceChunk.uasset
  Content/Blueprints/ChunkGen/BP_InstancedBuildings.uasset
  Content/Blueprints/InteractiveObjectManager/BP_InteractiveObjectManager.uasset
  Content/Maps/RayTestMap/AudioManager.umap
  Content/Materials/TestMaterials/M_BuildingShaderTest.uasset
Labels: progress

#81 import building class d(v3.8.4)
  Content/Geometry/Meshes/Environment/Materials/MI_building_class_D_02.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_building_class_D_02.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_D_02/T_SM_building_classs_07_AORMT.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_D_02/T_SM_building_classs_07_BC.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_D_02/T_SM_building_classs_07_EM.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_D_02/T_SM_building_classs_07_N.uasset
Labels: enhancement

#83 V3.8.6 Instance Material & Audio interaction
  Content/Blueprints/BP_AudioManager.uasset
  Content/Blueprints/ChunkGen/BP_InstancedBuildings.uasset
  Content/Geometry/Meshes/Environment/Materials/M_Master.uasset
  Content/Maps/TestMaps/ChunkGeneration.umap
Labels: progress

#84 Rework of Player Collision Particles (V3.8.1)
  Content/Effects/Materials/M_PixelSource.uasset
  Content/Effects/Materials/M_Smoke.uasset
  Content/Effects/ParticleSystems/PS_PlayerCollision.uasset
  Content/Effects/Textures/PixelTexture.uasset
Labels: progress

#82 Main Menu opdate.
  Content/Blueprints/MainMenu_CharacterMovement/ABP_CharacterMainMenu.uasset
  Content/Blueprints/MainMenu_CharacterMovement/BP_MenuCharacterMov.uasset
  Content/Blueprints/Menu/BP_MenuCharacter.uasset
  Content/Maps/Menu/MainMenu.umap
  Content/Maps/Menu/WBP_MainMenu.uasset
  Content/Widget/Credits.uasset
Labels: progress

#85 Billboard drone test (V3.9.1)
  Content/Blueprints/Billboards/BP_Billboards.uasset
  Content/Blueprints/feature_score_system/BP_Save_Data.uasset
  Content/Effects/Materials/M_Hologram_Static.uasset
  Content/Effects/Materials/M_Hologram_moving.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Billboard_01.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Billboard_02.uasset
  Content/Maps/TestMaps/Billboards.umap
Labels: enhancement, progress

#89 V3.10.1 VR input
  Content/Blueprints/feature_playermovement_refactor/BP_Flying_Character_VRMovement.uasset
Labels: enhancement

#90 Menu update, recalibration added and commented (V3.10.1)
  Content/Blueprints/Billboards/BP_Billboards.uasset
  Content/Blueprints/Menu/BP_MainMenu.uasset
  Content/Blueprints/Menu/BP_Recalibrate.uasset
  Content/Maps/Menu/MainMenu.umap
  Content/Maps/Menu/WBP_MainMenu.uasset
  Content/Widget/WBP_MainMenu.uasset
  Content/Widget/WBP_Recalibrate.uasset
Labels: enhancement, progress

#91 Feature scoreboard
  Content/Blueprints/ChunkGen/BP_ChunkGenerator_Tube_InstanceChunk.uasset
  Content/Blueprints/feature_hexcoin_pickup/BP_Hexcoin.uasset
  Content/Blueprints/feature_hexcoin_spawning/BP_Hexcoin_Spawn.uasset
  Content/Blueprints/feature_score_system/BP_Character.uasset
  Content/Blueprints/feature_score_system/BP_Save_Data.uasset
  Content/Blueprints/feature_scoreboard/BP_playerScoreData.uasset
  Content/Blueprints/feature_scoreboard/line.uasset
  Content/Blueprints/feature_scoreboard/scoreboard.uasset
Labels: progress

#93 Menu updated, sounds en Don model movement (v3.11.1)
  Content/Blueprints/MainMenu_CharacterMovement/BP_MenuCharacterMov.uasset
  Content/Blueprints/Menu/BP_MainMenu.uasset
  Content/Blueprints/Menu/BP_MenuCharacter.uasset
  Content/Maps/Menu/MainMenu.umap
Labels: enhancement, progress

#94 V3.11.2 Added coupled UI values
  Content/Blueprints/Billboards/BP_Billboards.uasset
  Content/Blueprints/feature_playermovement_refactor/BP_Flying_Character.uasset
  Content/Blueprints/feature_score_system/BP_Save_Data.uasset
  Content/Effects/Materials/M_Hologram_UI.uasset
  Content/Effects/Textures/Misc/UI_Final.uasset
  Content/Maps/Menu/MainMenu.umap
  Content/Maps/TestMaps/ChunkGeneration.umap
Labels: enhancement, progress

#95 Changes to buildingmanager, import Lotte buildings and highway fix
  Content/Blueprints/BuildingClass/BP_BuildingManager.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Building_Class_C_03.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Building_Class_D_03.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_Building_class_D_04.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_tram.uasset
  Content/Geometry/Meshes/Environment/Materials/MI_tram_tunnel.uasset
  Content/Geometry/Meshes/Environment/Meshes/MiscObjects/SM_Highway_Highway.uasset
  Content/Geometry/Meshes/Environment/Meshes/MiscObjects/SM_Tram_Tunnel.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_Class_D_03.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_Class_D_04.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_class_C_03.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Bulding_Class_D_03.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_c_03/T_Building_Class_C_03_AORMT.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_c_03/T_Building_Class_C_03_BC.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_c_03/T_Building_Class_C_03_EM.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_c_03/T_Building_Class_C_03_N.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_d_04/T_SM_Building_class_D_04_AORMT.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_d_04/T_SM_Building_class_D_04_BC.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_d_04/T_SM_Building_class_D_04_EM.uasset
  Content/Geometry/Meshes/Environment/Textures/building_class_d_04/T_SM_Building_class_D_04_N.uasset
  Content/Materials/M_WorldBG.uasset
Labels: enhancement, progress

#96 re-added jetpack to flying_character bp
  Content/Blueprints/feature_playermovement_refactor/BP_Flying_Character.uasset
  Content/Blueprints/feature_playermovement_refactor/BP_Flying_Character2.uasset
Labels: progress

#97 chunkgen changes and buildingmanager update
  Content/Blueprints/BuildingClass/BP_BuildingManager.uasset
  Content/Geometry/Meshes/Environment/Meshes/SM_Building_class_B_06.uasset
  Content/Maps/TestMaps/ChunkGeneration.umap
Labels: enhancement, progress

#100 Hoverbike (v3.11.1)
  Content/Geometry/Meshes/Environment/Materials/hoverbike_body.uasset
  Content/Geometry/Meshes/Environment/Materials/hoverbike_thrusters.uasset
  Content/Maps/Menu/MainMenu.umap
  Content/Meshes/Vehicles/Hoverbike/materials/hoverbike_body.uasset
  Content/Meshes/Vehicles/Hoverbike/materials/hoverbike_thrusters.uasset
  Content/Meshes/Vehicles/Hoverbike/meshes/hoverbike_merged_body_low001.uasset
  Content/Meshes/Vehicles/Hoverbike/meshes/hoverbike_merged_right_thruster_low001.uasset
  Content/Meshes/Vehicles/Hoverbike/textures/hoverbike_body/T_hoverbike_hoverbike_body_AO_R_MT.uasset
  Content/Meshes/Vehicles/Hoverbike/textures/hoverbike_body/T_hoverbike_hoverbike_body_BC.uasset
  Content/Meshes/Vehicles/Hoverbike/textures/hoverbike_body/T_hoverbike_hoverbike_body_EM.uasset
  Content/Meshes/Vehicles/Hoverbike/textures/hoverbike_body/T_hoverbike_hoverbike_body_N.uasset
  Content/Meshes/Vehicles/Hoverbike/textures/hoverbike_thrusters/T_hoverbike_hoverbike_thrusters_AO_R_MT.uasset
  Content/Meshes/Vehicles/Hoverbike/textures/hoverbike_thrusters/T_hoverbike_hoverbike_thrusters_BC.uasset
  Content/Meshes/Vehicles/Hoverbike/textures/hoverbike_thrusters/T_hoverbike_hoverbike_thrusters_EM.uasset
  Content/Meshes/Vehicles/Hoverbike/textures/hoverbike_thrusters/T_hoverbike_hoverbike_thrusters_N.uasset
Labels: enhancement
